// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

#ifndef PROTOBUF_proto_2faction_2eproto__INCLUDED
#define PROTOBUF_proto_2faction_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class BaseResp;
class BaseRespDefaultTypeInternal;
extern BaseRespDefaultTypeInternal _BaseResp_default_instance_;
class FollowRequest;
class FollowRequestDefaultTypeInternal;
extern FollowRequestDefaultTypeInternal _FollowRequest_default_instance_;
class FollowResponse;
class FollowResponseDefaultTypeInternal;
extern FollowResponseDefaultTypeInternal _FollowResponse_default_instance_;
class GetFollowListRequest;
class GetFollowListRequestDefaultTypeInternal;
extern GetFollowListRequestDefaultTypeInternal _GetFollowListRequest_default_instance_;
class GetFollowListResponse;
class GetFollowListResponseDefaultTypeInternal;
extern GetFollowListResponseDefaultTypeInternal _GetFollowListResponse_default_instance_;
class MGetFollowCountRequest;
class MGetFollowCountRequestDefaultTypeInternal;
extern MGetFollowCountRequestDefaultTypeInternal _MGetFollowCountRequest_default_instance_;
class MGetFollowCountResponse;
class MGetFollowCountResponseDefaultTypeInternal;
extern MGetFollowCountResponseDefaultTypeInternal _MGetFollowCountResponse_default_instance_;
class MGetFollowCountResponse_FollowerCountEntry;
class MGetFollowCountResponse_FollowerCountEntryDefaultTypeInternal;
extern MGetFollowCountResponse_FollowerCountEntryDefaultTypeInternal _MGetFollowCountResponse_FollowerCountEntry_default_instance_;
class MGetFollowCountResponse_FollowingCountEntry;
class MGetFollowCountResponse_FollowingCountEntryDefaultTypeInternal;
extern MGetFollowCountResponse_FollowingCountEntryDefaultTypeInternal _MGetFollowCountResponse_FollowingCountEntry_default_instance_;
class MGetFollowCountResponse_FriendCountEntry;
class MGetFollowCountResponse_FriendCountEntryDefaultTypeInternal;
extern MGetFollowCountResponse_FriendCountEntryDefaultTypeInternal _MGetFollowCountResponse_FriendCountEntry_default_instance_;
class MIsFollowRequest;
class MIsFollowRequestDefaultTypeInternal;
extern MIsFollowRequestDefaultTypeInternal _MIsFollowRequest_default_instance_;
class MIsFollowResponse;
class MIsFollowResponseDefaultTypeInternal;
extern MIsFollowResponseDefaultTypeInternal _MIsFollowResponse_default_instance_;
class MIsFollowResponse_IsFollowerEntry;
class MIsFollowResponse_IsFollowerEntryDefaultTypeInternal;
extern MIsFollowResponse_IsFollowerEntryDefaultTypeInternal _MIsFollowResponse_IsFollowerEntry_default_instance_;

namespace protobuf_proto_2faction_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_proto_2faction_2eproto

enum StatusCode {
  StatusCode_Not_Use = 0,
  Success = 1000,
  Server_Error = 1001,
  Param_Error = 1002,
  OverFrequency_Error = 1003,
  OverLimit_Error = 1004,
  Duplicate_Error = 1005,
  RetryTime_Error = 1006,
  StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool StatusCode_IsValid(int value);
const StatusCode StatusCode_MIN = StatusCode_Not_Use;
const StatusCode StatusCode_MAX = RetryTime_Error;
const int StatusCode_ARRAYSIZE = StatusCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* StatusCode_descriptor();
inline const ::std::string& StatusCode_Name(StatusCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    StatusCode_descriptor(), value);
}
inline bool StatusCode_Parse(
    const ::std::string& name, StatusCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<StatusCode>(
    StatusCode_descriptor(), name, value);
}
// ===================================================================

class BaseResp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BaseResp) */ {
 public:
  BaseResp();
  virtual ~BaseResp();

  BaseResp(const BaseResp& from);

  inline BaseResp& operator=(const BaseResp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseResp& default_instance();

  static inline const BaseResp* internal_default_instance() {
    return reinterpret_cast<const BaseResp*>(
               &_BaseResp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BaseResp* other);

  // implements Message ----------------------------------------------

  inline BaseResp* New() const PROTOBUF_FINAL { return New(NULL); }

  BaseResp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BaseResp& from);
  void MergeFrom(const BaseResp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BaseResp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string StatusMessage = 2;
  void clear_statusmessage();
  static const int kStatusMessageFieldNumber = 2;
  const ::std::string& statusmessage() const;
  void set_statusmessage(const ::std::string& value);
  #if LANG_CXX11
  void set_statusmessage(::std::string&& value);
  #endif
  void set_statusmessage(const char* value);
  void set_statusmessage(const char* value, size_t size);
  ::std::string* mutable_statusmessage();
  ::std::string* release_statusmessage();
  void set_allocated_statusmessage(::std::string* statusmessage);

  // .StatusCode StatusCode = 1;
  void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  ::StatusCode statuscode() const;
  void set_statuscode(::StatusCode value);

  // @@protoc_insertion_point(class_scope:BaseResp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr statusmessage_;
  int statuscode_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MIsFollowRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MIsFollowRequest) */ {
 public:
  MIsFollowRequest();
  virtual ~MIsFollowRequest();

  MIsFollowRequest(const MIsFollowRequest& from);

  inline MIsFollowRequest& operator=(const MIsFollowRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MIsFollowRequest& default_instance();

  static inline const MIsFollowRequest* internal_default_instance() {
    return reinterpret_cast<const MIsFollowRequest*>(
               &_MIsFollowRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MIsFollowRequest* other);

  // implements Message ----------------------------------------------

  inline MIsFollowRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  MIsFollowRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MIsFollowRequest& from);
  void MergeFrom(const MIsFollowRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MIsFollowRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 to_user_ids = 2;
  int to_user_ids_size() const;
  void clear_to_user_ids();
  static const int kToUserIdsFieldNumber = 2;
  ::google::protobuf::int64 to_user_ids(int index) const;
  void set_to_user_ids(int index, ::google::protobuf::int64 value);
  void add_to_user_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      to_user_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_to_user_ids();

  // int64 from_user_id = 1;
  void clear_from_user_id();
  static const int kFromUserIdFieldNumber = 1;
  ::google::protobuf::int64 from_user_id() const;
  void set_from_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MIsFollowRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > to_user_ids_;
  mutable int _to_user_ids_cached_byte_size_;
  ::google::protobuf::int64 from_user_id_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class MIsFollowResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MIsFollowResponse) */ {
 public:
  MIsFollowResponse();
  virtual ~MIsFollowResponse();

  MIsFollowResponse(const MIsFollowResponse& from);

  inline MIsFollowResponse& operator=(const MIsFollowResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MIsFollowResponse& default_instance();

  static inline const MIsFollowResponse* internal_default_instance() {
    return reinterpret_cast<const MIsFollowResponse*>(
               &_MIsFollowResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(MIsFollowResponse* other);

  // implements Message ----------------------------------------------

  inline MIsFollowResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  MIsFollowResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MIsFollowResponse& from);
  void MergeFrom(const MIsFollowResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MIsFollowResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int64, bool> is_follower = 1;
  int is_follower_size() const;
  void clear_is_follower();
  static const int kIsFollowerFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int64, bool >&
      is_follower() const;
  ::google::protobuf::Map< ::google::protobuf::int64, bool >*
      mutable_is_follower();

  // .BaseResp baseResp = 255;
  bool has_baseresp() const;
  void clear_baseresp();
  static const int kBaseRespFieldNumber = 255;
  const ::BaseResp& baseresp() const;
  ::BaseResp* mutable_baseresp();
  ::BaseResp* release_baseresp();
  void set_allocated_baseresp(::BaseResp* baseresp);

  // @@protoc_insertion_point(class_scope:MIsFollowResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class MIsFollowResponse_IsFollowerEntry : public ::google::protobuf::internal::MapEntry<MIsFollowResponse_IsFollowerEntry, 
      ::google::protobuf::int64, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<MIsFollowResponse_IsFollowerEntry, 
      ::google::protobuf::int64, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
      0 > SuperType;
    MIsFollowResponse_IsFollowerEntry();
    MIsFollowResponse_IsFollowerEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const MIsFollowResponse_IsFollowerEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_MIsFollowResponse_IsFollowerEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      MIsFollowResponse_IsFollowerEntry,
      ::google::protobuf::int64, bool,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_BOOL,
      0 > is_follower_;
  private:
  ::BaseResp* baseresp_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetFollowListRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetFollowListRequest) */ {
 public:
  GetFollowListRequest();
  virtual ~GetFollowListRequest();

  GetFollowListRequest(const GetFollowListRequest& from);

  inline GetFollowListRequest& operator=(const GetFollowListRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFollowListRequest& default_instance();

  static inline const GetFollowListRequest* internal_default_instance() {
    return reinterpret_cast<const GetFollowListRequest*>(
               &_GetFollowListRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(GetFollowListRequest* other);

  // implements Message ----------------------------------------------

  inline GetFollowListRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetFollowListRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetFollowListRequest& from);
  void MergeFrom(const GetFollowListRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetFollowListRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // int64 min_time = 2;
  void clear_min_time();
  static const int kMinTimeFieldNumber = 2;
  ::google::protobuf::int64 min_time() const;
  void set_min_time(::google::protobuf::int64 value);

  // int64 max_time = 3;
  void clear_max_time();
  static const int kMaxTimeFieldNumber = 3;
  ::google::protobuf::int64 max_time() const;
  void set_max_time(::google::protobuf::int64 value);

  // int64 count = 4;
  void clear_count();
  static const int kCountFieldNumber = 4;
  ::google::protobuf::int64 count() const;
  void set_count(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:GetFollowListRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 user_id_;
  ::google::protobuf::int64 min_time_;
  ::google::protobuf::int64 max_time_;
  ::google::protobuf::int64 count_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetFollowListResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetFollowListResponse) */ {
 public:
  GetFollowListResponse();
  virtual ~GetFollowListResponse();

  GetFollowListResponse(const GetFollowListResponse& from);

  inline GetFollowListResponse& operator=(const GetFollowListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetFollowListResponse& default_instance();

  static inline const GetFollowListResponse* internal_default_instance() {
    return reinterpret_cast<const GetFollowListResponse*>(
               &_GetFollowListResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(GetFollowListResponse* other);

  // implements Message ----------------------------------------------

  inline GetFollowListResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetFollowListResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetFollowListResponse& from);
  void MergeFrom(const GetFollowListResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetFollowListResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 user_ids = 1;
  int user_ids_size() const;
  void clear_user_ids();
  static const int kUserIdsFieldNumber = 1;
  ::google::protobuf::int64 user_ids(int index) const;
  void set_user_ids(int index, ::google::protobuf::int64 value);
  void add_user_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      user_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_user_ids();

  // .BaseResp baseResp = 255;
  bool has_baseresp() const;
  void clear_baseresp();
  static const int kBaseRespFieldNumber = 255;
  const ::BaseResp& baseresp() const;
  ::BaseResp* mutable_baseresp();
  ::BaseResp* release_baseresp();
  void set_allocated_baseresp(::BaseResp* baseresp);

  // int64 total = 2;
  void clear_total();
  static const int kTotalFieldNumber = 2;
  ::google::protobuf::int64 total() const;
  void set_total(::google::protobuf::int64 value);

  // bool has_more = 3;
  void clear_has_more();
  static const int kHasMoreFieldNumber = 3;
  bool has_more() const;
  void set_has_more(bool value);

  // @@protoc_insertion_point(class_scope:GetFollowListResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > user_ids_;
  mutable int _user_ids_cached_byte_size_;
  ::BaseResp* baseresp_;
  ::google::protobuf::int64 total_;
  bool has_more_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MGetFollowCountRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MGetFollowCountRequest) */ {
 public:
  MGetFollowCountRequest();
  virtual ~MGetFollowCountRequest();

  MGetFollowCountRequest(const MGetFollowCountRequest& from);

  inline MGetFollowCountRequest& operator=(const MGetFollowCountRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MGetFollowCountRequest& default_instance();

  static inline const MGetFollowCountRequest* internal_default_instance() {
    return reinterpret_cast<const MGetFollowCountRequest*>(
               &_MGetFollowCountRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(MGetFollowCountRequest* other);

  // implements Message ----------------------------------------------

  inline MGetFollowCountRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  MGetFollowCountRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MGetFollowCountRequest& from);
  void MergeFrom(const MGetFollowCountRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MGetFollowCountRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 user_ids = 1;
  int user_ids_size() const;
  void clear_user_ids();
  static const int kUserIdsFieldNumber = 1;
  ::google::protobuf::int64 user_ids(int index) const;
  void set_user_ids(int index, ::google::protobuf::int64 value);
  void add_user_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      user_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_user_ids();

  // bool need_following = 2;
  void clear_need_following();
  static const int kNeedFollowingFieldNumber = 2;
  bool need_following() const;
  void set_need_following(bool value);

  // bool need_follower = 3;
  void clear_need_follower();
  static const int kNeedFollowerFieldNumber = 3;
  bool need_follower() const;
  void set_need_follower(bool value);

  // bool need_friend = 4;
  void clear_need_friend();
  static const int kNeedFriendFieldNumber = 4;
  bool need_friend() const;
  void set_need_friend(bool value);

  // @@protoc_insertion_point(class_scope:MGetFollowCountRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > user_ids_;
  mutable int _user_ids_cached_byte_size_;
  bool need_following_;
  bool need_follower_;
  bool need_friend_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------


// -------------------------------------------------------------------


// -------------------------------------------------------------------

class MGetFollowCountResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MGetFollowCountResponse) */ {
 public:
  MGetFollowCountResponse();
  virtual ~MGetFollowCountResponse();

  MGetFollowCountResponse(const MGetFollowCountResponse& from);

  inline MGetFollowCountResponse& operator=(const MGetFollowCountResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MGetFollowCountResponse& default_instance();

  static inline const MGetFollowCountResponse* internal_default_instance() {
    return reinterpret_cast<const MGetFollowCountResponse*>(
               &_MGetFollowCountResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(MGetFollowCountResponse* other);

  // implements Message ----------------------------------------------

  inline MGetFollowCountResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  MGetFollowCountResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MGetFollowCountResponse& from);
  void MergeFrom(const MGetFollowCountResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MGetFollowCountResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int64, int64> following_count = 1;
  int following_count_size() const;
  void clear_following_count();
  static const int kFollowingCountFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      following_count() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_following_count();

  // map<int64, int64> follower_count = 2;
  int follower_count_size() const;
  void clear_follower_count();
  static const int kFollowerCountFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      follower_count() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_follower_count();

  // map<int64, int64> friend_count = 3;
  int friend_count_size() const;
  void clear_friend_count();
  static const int kFriendCountFieldNumber = 3;
  const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
      friend_count() const;
  ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
      mutable_friend_count();

  // .BaseResp baseResp = 255;
  bool has_baseresp() const;
  void clear_baseresp();
  static const int kBaseRespFieldNumber = 255;
  const ::BaseResp& baseresp() const;
  ::BaseResp* mutable_baseresp();
  ::BaseResp* release_baseresp();
  void set_allocated_baseresp(::BaseResp* baseresp);

  // @@protoc_insertion_point(class_scope:MGetFollowCountResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class MGetFollowCountResponse_FollowingCountEntry : public ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FollowingCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FollowingCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > SuperType;
    MGetFollowCountResponse_FollowingCountEntry();
    MGetFollowCountResponse_FollowingCountEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const MGetFollowCountResponse_FollowingCountEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_MGetFollowCountResponse_FollowingCountEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      MGetFollowCountResponse_FollowingCountEntry,
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > following_count_;
  private:
  public:
  class MGetFollowCountResponse_FollowerCountEntry : public ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FollowerCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FollowerCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > SuperType;
    MGetFollowCountResponse_FollowerCountEntry();
    MGetFollowCountResponse_FollowerCountEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const MGetFollowCountResponse_FollowerCountEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_MGetFollowCountResponse_FollowerCountEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      MGetFollowCountResponse_FollowerCountEntry,
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > follower_count_;
  private:
  public:
  class MGetFollowCountResponse_FriendCountEntry : public ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FriendCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<MGetFollowCountResponse_FriendCountEntry, 
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > SuperType;
    MGetFollowCountResponse_FriendCountEntry();
    MGetFollowCountResponse_FriendCountEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const MGetFollowCountResponse_FriendCountEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_MGetFollowCountResponse_FriendCountEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  ::google::protobuf::internal::MapField<
      MGetFollowCountResponse_FriendCountEntry,
      ::google::protobuf::int64, ::google::protobuf::int64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      0 > friend_count_;
  private:
  ::BaseResp* baseresp_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FollowRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FollowRequest) */ {
 public:
  FollowRequest();
  virtual ~FollowRequest();

  FollowRequest(const FollowRequest& from);

  inline FollowRequest& operator=(const FollowRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowRequest& default_instance();

  static inline const FollowRequest* internal_default_instance() {
    return reinterpret_cast<const FollowRequest*>(
               &_FollowRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(FollowRequest* other);

  // implements Message ----------------------------------------------

  inline FollowRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  FollowRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FollowRequest& from);
  void MergeFrom(const FollowRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FollowRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 from_user_id = 1;
  void clear_from_user_id();
  static const int kFromUserIdFieldNumber = 1;
  ::google::protobuf::int64 from_user_id() const;
  void set_from_user_id(::google::protobuf::int64 value);

  // int64 to_user_id = 2;
  void clear_to_user_id();
  static const int kToUserIdFieldNumber = 2;
  ::google::protobuf::int64 to_user_id() const;
  void set_to_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:FollowRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 from_user_id_;
  ::google::protobuf::int64 to_user_id_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FollowResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:FollowResponse) */ {
 public:
  FollowResponse();
  virtual ~FollowResponse();

  FollowResponse(const FollowResponse& from);

  inline FollowResponse& operator=(const FollowResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FollowResponse& default_instance();

  static inline const FollowResponse* internal_default_instance() {
    return reinterpret_cast<const FollowResponse*>(
               &_FollowResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  void Swap(FollowResponse* other);

  // implements Message ----------------------------------------------

  inline FollowResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  FollowResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FollowResponse& from);
  void MergeFrom(const FollowResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FollowResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .BaseResp baseResp = 255;
  bool has_baseresp() const;
  void clear_baseresp();
  static const int kBaseRespFieldNumber = 255;
  const ::BaseResp& baseresp() const;
  ::BaseResp* mutable_baseresp();
  ::BaseResp* release_baseresp();
  void set_allocated_baseresp(::BaseResp* baseresp);

  // @@protoc_insertion_point(class_scope:FollowResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::BaseResp* baseresp_;
  mutable int _cached_size_;
  friend struct protobuf_proto_2faction_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// BaseResp

// .StatusCode StatusCode = 1;
inline void BaseResp::clear_statuscode() {
  statuscode_ = 0;
}
inline ::StatusCode BaseResp::statuscode() const {
  // @@protoc_insertion_point(field_get:BaseResp.StatusCode)
  return static_cast< ::StatusCode >(statuscode_);
}
inline void BaseResp::set_statuscode(::StatusCode value) {
  
  statuscode_ = value;
  // @@protoc_insertion_point(field_set:BaseResp.StatusCode)
}

// string StatusMessage = 2;
inline void BaseResp::clear_statusmessage() {
  statusmessage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& BaseResp::statusmessage() const {
  // @@protoc_insertion_point(field_get:BaseResp.StatusMessage)
  return statusmessage_.GetNoArena();
}
inline void BaseResp::set_statusmessage(const ::std::string& value) {
  
  statusmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BaseResp.StatusMessage)
}
#if LANG_CXX11
inline void BaseResp::set_statusmessage(::std::string&& value) {
  
  statusmessage_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:BaseResp.StatusMessage)
}
#endif
inline void BaseResp::set_statusmessage(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  statusmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BaseResp.StatusMessage)
}
inline void BaseResp::set_statusmessage(const char* value, size_t size) {
  
  statusmessage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BaseResp.StatusMessage)
}
inline ::std::string* BaseResp::mutable_statusmessage() {
  
  // @@protoc_insertion_point(field_mutable:BaseResp.StatusMessage)
  return statusmessage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BaseResp::release_statusmessage() {
  // @@protoc_insertion_point(field_release:BaseResp.StatusMessage)
  
  return statusmessage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BaseResp::set_allocated_statusmessage(::std::string* statusmessage) {
  if (statusmessage != NULL) {
    
  } else {
    
  }
  statusmessage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), statusmessage);
  // @@protoc_insertion_point(field_set_allocated:BaseResp.StatusMessage)
}

// -------------------------------------------------------------------

// MIsFollowRequest

// int64 from_user_id = 1;
inline void MIsFollowRequest::clear_from_user_id() {
  from_user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MIsFollowRequest::from_user_id() const {
  // @@protoc_insertion_point(field_get:MIsFollowRequest.from_user_id)
  return from_user_id_;
}
inline void MIsFollowRequest::set_from_user_id(::google::protobuf::int64 value) {
  
  from_user_id_ = value;
  // @@protoc_insertion_point(field_set:MIsFollowRequest.from_user_id)
}

// repeated int64 to_user_ids = 2;
inline int MIsFollowRequest::to_user_ids_size() const {
  return to_user_ids_.size();
}
inline void MIsFollowRequest::clear_to_user_ids() {
  to_user_ids_.Clear();
}
inline ::google::protobuf::int64 MIsFollowRequest::to_user_ids(int index) const {
  // @@protoc_insertion_point(field_get:MIsFollowRequest.to_user_ids)
  return to_user_ids_.Get(index);
}
inline void MIsFollowRequest::set_to_user_ids(int index, ::google::protobuf::int64 value) {
  to_user_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:MIsFollowRequest.to_user_ids)
}
inline void MIsFollowRequest::add_to_user_ids(::google::protobuf::int64 value) {
  to_user_ids_.Add(value);
  // @@protoc_insertion_point(field_add:MIsFollowRequest.to_user_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MIsFollowRequest::to_user_ids() const {
  // @@protoc_insertion_point(field_list:MIsFollowRequest.to_user_ids)
  return to_user_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MIsFollowRequest::mutable_to_user_ids() {
  // @@protoc_insertion_point(field_mutable_list:MIsFollowRequest.to_user_ids)
  return &to_user_ids_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MIsFollowResponse

// map<int64, bool> is_follower = 1;
inline int MIsFollowResponse::is_follower_size() const {
  return is_follower_.size();
}
inline void MIsFollowResponse::clear_is_follower() {
  is_follower_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, bool >&
MIsFollowResponse::is_follower() const {
  // @@protoc_insertion_point(field_map:MIsFollowResponse.is_follower)
  return is_follower_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, bool >*
MIsFollowResponse::mutable_is_follower() {
  // @@protoc_insertion_point(field_mutable_map:MIsFollowResponse.is_follower)
  return is_follower_.MutableMap();
}

// .BaseResp baseResp = 255;
inline bool MIsFollowResponse::has_baseresp() const {
  return this != internal_default_instance() && baseresp_ != NULL;
}
inline void MIsFollowResponse::clear_baseresp() {
  if (GetArenaNoVirtual() == NULL && baseresp_ != NULL) delete baseresp_;
  baseresp_ = NULL;
}
inline const ::BaseResp& MIsFollowResponse::baseresp() const {
  // @@protoc_insertion_point(field_get:MIsFollowResponse.baseResp)
  return baseresp_ != NULL ? *baseresp_
                         : *::BaseResp::internal_default_instance();
}
inline ::BaseResp* MIsFollowResponse::mutable_baseresp() {
  
  if (baseresp_ == NULL) {
    baseresp_ = new ::BaseResp;
  }
  // @@protoc_insertion_point(field_mutable:MIsFollowResponse.baseResp)
  return baseresp_;
}
inline ::BaseResp* MIsFollowResponse::release_baseresp() {
  // @@protoc_insertion_point(field_release:MIsFollowResponse.baseResp)
  
  ::BaseResp* temp = baseresp_;
  baseresp_ = NULL;
  return temp;
}
inline void MIsFollowResponse::set_allocated_baseresp(::BaseResp* baseresp) {
  delete baseresp_;
  baseresp_ = baseresp;
  if (baseresp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MIsFollowResponse.baseResp)
}

// -------------------------------------------------------------------

// GetFollowListRequest

// int64 user_id = 1;
inline void GetFollowListRequest::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GetFollowListRequest::user_id() const {
  // @@protoc_insertion_point(field_get:GetFollowListRequest.user_id)
  return user_id_;
}
inline void GetFollowListRequest::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListRequest.user_id)
}

// int64 min_time = 2;
inline void GetFollowListRequest::clear_min_time() {
  min_time_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GetFollowListRequest::min_time() const {
  // @@protoc_insertion_point(field_get:GetFollowListRequest.min_time)
  return min_time_;
}
inline void GetFollowListRequest::set_min_time(::google::protobuf::int64 value) {
  
  min_time_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListRequest.min_time)
}

// int64 max_time = 3;
inline void GetFollowListRequest::clear_max_time() {
  max_time_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GetFollowListRequest::max_time() const {
  // @@protoc_insertion_point(field_get:GetFollowListRequest.max_time)
  return max_time_;
}
inline void GetFollowListRequest::set_max_time(::google::protobuf::int64 value) {
  
  max_time_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListRequest.max_time)
}

// int64 count = 4;
inline void GetFollowListRequest::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GetFollowListRequest::count() const {
  // @@protoc_insertion_point(field_get:GetFollowListRequest.count)
  return count_;
}
inline void GetFollowListRequest::set_count(::google::protobuf::int64 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListRequest.count)
}

// -------------------------------------------------------------------

// GetFollowListResponse

// repeated int64 user_ids = 1;
inline int GetFollowListResponse::user_ids_size() const {
  return user_ids_.size();
}
inline void GetFollowListResponse::clear_user_ids() {
  user_ids_.Clear();
}
inline ::google::protobuf::int64 GetFollowListResponse::user_ids(int index) const {
  // @@protoc_insertion_point(field_get:GetFollowListResponse.user_ids)
  return user_ids_.Get(index);
}
inline void GetFollowListResponse::set_user_ids(int index, ::google::protobuf::int64 value) {
  user_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:GetFollowListResponse.user_ids)
}
inline void GetFollowListResponse::add_user_ids(::google::protobuf::int64 value) {
  user_ids_.Add(value);
  // @@protoc_insertion_point(field_add:GetFollowListResponse.user_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
GetFollowListResponse::user_ids() const {
  // @@protoc_insertion_point(field_list:GetFollowListResponse.user_ids)
  return user_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
GetFollowListResponse::mutable_user_ids() {
  // @@protoc_insertion_point(field_mutable_list:GetFollowListResponse.user_ids)
  return &user_ids_;
}

// int64 total = 2;
inline void GetFollowListResponse::clear_total() {
  total_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 GetFollowListResponse::total() const {
  // @@protoc_insertion_point(field_get:GetFollowListResponse.total)
  return total_;
}
inline void GetFollowListResponse::set_total(::google::protobuf::int64 value) {
  
  total_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListResponse.total)
}

// bool has_more = 3;
inline void GetFollowListResponse::clear_has_more() {
  has_more_ = false;
}
inline bool GetFollowListResponse::has_more() const {
  // @@protoc_insertion_point(field_get:GetFollowListResponse.has_more)
  return has_more_;
}
inline void GetFollowListResponse::set_has_more(bool value) {
  
  has_more_ = value;
  // @@protoc_insertion_point(field_set:GetFollowListResponse.has_more)
}

// .BaseResp baseResp = 255;
inline bool GetFollowListResponse::has_baseresp() const {
  return this != internal_default_instance() && baseresp_ != NULL;
}
inline void GetFollowListResponse::clear_baseresp() {
  if (GetArenaNoVirtual() == NULL && baseresp_ != NULL) delete baseresp_;
  baseresp_ = NULL;
}
inline const ::BaseResp& GetFollowListResponse::baseresp() const {
  // @@protoc_insertion_point(field_get:GetFollowListResponse.baseResp)
  return baseresp_ != NULL ? *baseresp_
                         : *::BaseResp::internal_default_instance();
}
inline ::BaseResp* GetFollowListResponse::mutable_baseresp() {
  
  if (baseresp_ == NULL) {
    baseresp_ = new ::BaseResp;
  }
  // @@protoc_insertion_point(field_mutable:GetFollowListResponse.baseResp)
  return baseresp_;
}
inline ::BaseResp* GetFollowListResponse::release_baseresp() {
  // @@protoc_insertion_point(field_release:GetFollowListResponse.baseResp)
  
  ::BaseResp* temp = baseresp_;
  baseresp_ = NULL;
  return temp;
}
inline void GetFollowListResponse::set_allocated_baseresp(::BaseResp* baseresp) {
  delete baseresp_;
  baseresp_ = baseresp;
  if (baseresp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:GetFollowListResponse.baseResp)
}

// -------------------------------------------------------------------

// MGetFollowCountRequest

// repeated int64 user_ids = 1;
inline int MGetFollowCountRequest::user_ids_size() const {
  return user_ids_.size();
}
inline void MGetFollowCountRequest::clear_user_ids() {
  user_ids_.Clear();
}
inline ::google::protobuf::int64 MGetFollowCountRequest::user_ids(int index) const {
  // @@protoc_insertion_point(field_get:MGetFollowCountRequest.user_ids)
  return user_ids_.Get(index);
}
inline void MGetFollowCountRequest::set_user_ids(int index, ::google::protobuf::int64 value) {
  user_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:MGetFollowCountRequest.user_ids)
}
inline void MGetFollowCountRequest::add_user_ids(::google::protobuf::int64 value) {
  user_ids_.Add(value);
  // @@protoc_insertion_point(field_add:MGetFollowCountRequest.user_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
MGetFollowCountRequest::user_ids() const {
  // @@protoc_insertion_point(field_list:MGetFollowCountRequest.user_ids)
  return user_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
MGetFollowCountRequest::mutable_user_ids() {
  // @@protoc_insertion_point(field_mutable_list:MGetFollowCountRequest.user_ids)
  return &user_ids_;
}

// bool need_following = 2;
inline void MGetFollowCountRequest::clear_need_following() {
  need_following_ = false;
}
inline bool MGetFollowCountRequest::need_following() const {
  // @@protoc_insertion_point(field_get:MGetFollowCountRequest.need_following)
  return need_following_;
}
inline void MGetFollowCountRequest::set_need_following(bool value) {
  
  need_following_ = value;
  // @@protoc_insertion_point(field_set:MGetFollowCountRequest.need_following)
}

// bool need_follower = 3;
inline void MGetFollowCountRequest::clear_need_follower() {
  need_follower_ = false;
}
inline bool MGetFollowCountRequest::need_follower() const {
  // @@protoc_insertion_point(field_get:MGetFollowCountRequest.need_follower)
  return need_follower_;
}
inline void MGetFollowCountRequest::set_need_follower(bool value) {
  
  need_follower_ = value;
  // @@protoc_insertion_point(field_set:MGetFollowCountRequest.need_follower)
}

// bool need_friend = 4;
inline void MGetFollowCountRequest::clear_need_friend() {
  need_friend_ = false;
}
inline bool MGetFollowCountRequest::need_friend() const {
  // @@protoc_insertion_point(field_get:MGetFollowCountRequest.need_friend)
  return need_friend_;
}
inline void MGetFollowCountRequest::set_need_friend(bool value) {
  
  need_friend_ = value;
  // @@protoc_insertion_point(field_set:MGetFollowCountRequest.need_friend)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// MGetFollowCountResponse

// map<int64, int64> following_count = 1;
inline int MGetFollowCountResponse::following_count_size() const {
  return following_count_.size();
}
inline void MGetFollowCountResponse::clear_following_count() {
  following_count_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
MGetFollowCountResponse::following_count() const {
  // @@protoc_insertion_point(field_map:MGetFollowCountResponse.following_count)
  return following_count_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
MGetFollowCountResponse::mutable_following_count() {
  // @@protoc_insertion_point(field_mutable_map:MGetFollowCountResponse.following_count)
  return following_count_.MutableMap();
}

// map<int64, int64> follower_count = 2;
inline int MGetFollowCountResponse::follower_count_size() const {
  return follower_count_.size();
}
inline void MGetFollowCountResponse::clear_follower_count() {
  follower_count_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
MGetFollowCountResponse::follower_count() const {
  // @@protoc_insertion_point(field_map:MGetFollowCountResponse.follower_count)
  return follower_count_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
MGetFollowCountResponse::mutable_follower_count() {
  // @@protoc_insertion_point(field_mutable_map:MGetFollowCountResponse.follower_count)
  return follower_count_.MutableMap();
}

// map<int64, int64> friend_count = 3;
inline int MGetFollowCountResponse::friend_count_size() const {
  return friend_count_.size();
}
inline void MGetFollowCountResponse::clear_friend_count() {
  friend_count_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >&
MGetFollowCountResponse::friend_count() const {
  // @@protoc_insertion_point(field_map:MGetFollowCountResponse.friend_count)
  return friend_count_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int64, ::google::protobuf::int64 >*
MGetFollowCountResponse::mutable_friend_count() {
  // @@protoc_insertion_point(field_mutable_map:MGetFollowCountResponse.friend_count)
  return friend_count_.MutableMap();
}

// .BaseResp baseResp = 255;
inline bool MGetFollowCountResponse::has_baseresp() const {
  return this != internal_default_instance() && baseresp_ != NULL;
}
inline void MGetFollowCountResponse::clear_baseresp() {
  if (GetArenaNoVirtual() == NULL && baseresp_ != NULL) delete baseresp_;
  baseresp_ = NULL;
}
inline const ::BaseResp& MGetFollowCountResponse::baseresp() const {
  // @@protoc_insertion_point(field_get:MGetFollowCountResponse.baseResp)
  return baseresp_ != NULL ? *baseresp_
                         : *::BaseResp::internal_default_instance();
}
inline ::BaseResp* MGetFollowCountResponse::mutable_baseresp() {
  
  if (baseresp_ == NULL) {
    baseresp_ = new ::BaseResp;
  }
  // @@protoc_insertion_point(field_mutable:MGetFollowCountResponse.baseResp)
  return baseresp_;
}
inline ::BaseResp* MGetFollowCountResponse::release_baseresp() {
  // @@protoc_insertion_point(field_release:MGetFollowCountResponse.baseResp)
  
  ::BaseResp* temp = baseresp_;
  baseresp_ = NULL;
  return temp;
}
inline void MGetFollowCountResponse::set_allocated_baseresp(::BaseResp* baseresp) {
  delete baseresp_;
  baseresp_ = baseresp;
  if (baseresp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:MGetFollowCountResponse.baseResp)
}

// -------------------------------------------------------------------

// FollowRequest

// int64 from_user_id = 1;
inline void FollowRequest::clear_from_user_id() {
  from_user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 FollowRequest::from_user_id() const {
  // @@protoc_insertion_point(field_get:FollowRequest.from_user_id)
  return from_user_id_;
}
inline void FollowRequest::set_from_user_id(::google::protobuf::int64 value) {
  
  from_user_id_ = value;
  // @@protoc_insertion_point(field_set:FollowRequest.from_user_id)
}

// int64 to_user_id = 2;
inline void FollowRequest::clear_to_user_id() {
  to_user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 FollowRequest::to_user_id() const {
  // @@protoc_insertion_point(field_get:FollowRequest.to_user_id)
  return to_user_id_;
}
inline void FollowRequest::set_to_user_id(::google::protobuf::int64 value) {
  
  to_user_id_ = value;
  // @@protoc_insertion_point(field_set:FollowRequest.to_user_id)
}

// -------------------------------------------------------------------

// FollowResponse

// .BaseResp baseResp = 255;
inline bool FollowResponse::has_baseresp() const {
  return this != internal_default_instance() && baseresp_ != NULL;
}
inline void FollowResponse::clear_baseresp() {
  if (GetArenaNoVirtual() == NULL && baseresp_ != NULL) delete baseresp_;
  baseresp_ = NULL;
}
inline const ::BaseResp& FollowResponse::baseresp() const {
  // @@protoc_insertion_point(field_get:FollowResponse.baseResp)
  return baseresp_ != NULL ? *baseresp_
                         : *::BaseResp::internal_default_instance();
}
inline ::BaseResp* FollowResponse::mutable_baseresp() {
  
  if (baseresp_ == NULL) {
    baseresp_ = new ::BaseResp;
  }
  // @@protoc_insertion_point(field_mutable:FollowResponse.baseResp)
  return baseresp_;
}
inline ::BaseResp* FollowResponse::release_baseresp() {
  // @@protoc_insertion_point(field_release:FollowResponse.baseResp)
  
  ::BaseResp* temp = baseresp_;
  baseresp_ = NULL;
  return temp;
}
inline void FollowResponse::set_allocated_baseresp(::BaseResp* baseresp) {
  delete baseresp_;
  baseresp_ = baseresp;
  if (baseresp) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:FollowResponse.baseResp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::StatusCode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::StatusCode>() {
  return ::StatusCode_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2faction_2eproto__INCLUDED
