// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public final class Action {
  private Action() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FollowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MIsFollowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MIsFollowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MIsFollowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MIsFollowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MIsFollowResponse_IsFollowingEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MIsFollowResponse_IsFollowingEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MIsFollowResponse_IsFollowerEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MIsFollowResponse_IsFollowerEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFollowListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFollowListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetFollowListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetFollowListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MGetFollowCountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MGetFollowCountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MGetFollowCountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MGetFollowCountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MGetFollowCountResponse_FollowingCountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MGetFollowCountResponse_FollowingCountEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MGetFollowCountResponse_FollowerCountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MGetFollowCountResponse_FollowerCountEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MGetFollowCountResponse_FriendCountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MGetFollowCountResponse_FriendCountEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/action.proto\"B\n\010BaseResp\022\037\n\nStat" +
      "usCode\030\001 \001(\0162\013.StatusCode\022\025\n\rStatusMessa" +
      "ge\030\002 \001(\t\"9\n\rFollowRequest\022\024\n\014from_user_i" +
      "d\030\001 \001(\003\022\022\n\nto_user_id\030\002 \001(\003\".\n\016FollowRes" +
      "ponse\022\034\n\010baseResp\030\377\001 \001(\0132\t.BaseResp\"=\n\020M" +
      "IsFollowRequest\022\024\n\014from_user_id\030\001 \001(\003\022\023\n" +
      "\013to_user_ids\030\002 \003(\003\"\214\002\n\021MIsFollowResponse" +
      "\0229\n\014is_following\030\001 \003(\0132#.MIsFollowRespon" +
      "se.IsFollowingEntry\0227\n\013is_follower\030\002 \003(\013" +
      "2\".MIsFollowResponse.IsFollowerEntry\022\034\n\010",
      "baseResp\030\377\001 \001(\0132\t.BaseResp\0322\n\020IsFollowin" +
      "gEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\010:\0028\001\0321" +
      "\n\017IsFollowerEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030" +
      "\002 \001(\010:\0028\001\"Z\n\024GetFollowListRequest\022\017\n\007use" +
      "r_id\030\001 \001(\003\022\020\n\010min_time\030\002 \001(\003\022\020\n\010max_time" +
      "\030\003 \001(\003\022\r\n\005count\030\004 \001(\003\"h\n\025GetFollowListRe" +
      "sponse\022\020\n\010user_ids\030\001 \003(\003\022\r\n\005total\030\002 \001(\003\022" +
      "\020\n\010has_more\030\003 \001(\010\022\034\n\010baseResp\030\377\001 \001(\0132\t.B" +
      "aseResp\"n\n\026MGetFollowCountRequest\022\020\n\010use" +
      "r_ids\030\001 \003(\003\022\026\n\016need_following\030\002 \001(\010\022\025\n\rn",
      "eed_follower\030\003 \001(\010\022\023\n\013need_friend\030\004 \001(\010\"" +
      "\245\003\n\027MGetFollowCountResponse\022E\n\017following" +
      "_count\030\001 \003(\0132,.MGetFollowCountResponse.F" +
      "ollowingCountEntry\022C\n\016follower_count\030\002 \003" +
      "(\0132+.MGetFollowCountResponse.FollowerCou" +
      "ntEntry\022?\n\014friend_count\030\003 \003(\0132).MGetFoll" +
      "owCountResponse.FriendCountEntry\022\034\n\010base" +
      "Resp\030\377\001 \001(\0132\t.BaseResp\0325\n\023FollowingCount" +
      "Entry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\003:\0028\001\0324\n" +
      "\022FollowerCountEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005valu",
      "e\030\002 \001(\003:\0028\001\0322\n\020FriendCountEntry\022\013\n\003key\030\001" +
      " \001(\003\022\r\n\005value\030\002 \001(\003:\0028\001*\263\001\n\nStatusCode\022\026" +
      "\n\022StatusCode_Not_Use\020\000\022\014\n\007Success\020\350\007\022\021\n\014" +
      "Server_Error\020\351\007\022\020\n\013Param_Error\020\352\007\022\030\n\023Ove" +
      "rFrequency_Error\020\353\007\022\024\n\017OverLimit_Error\020\354" +
      "\007\022\024\n\017Duplicate_Error\020\355\007\022\024\n\017RetryTime_Err" +
      "or\020\356\0072\356\003\n\rActionService\022+\n\006Follow\022\016.Foll" +
      "owRequest\032\017.FollowResponse\"\000\022-\n\010Unfollow" +
      "\022\016.FollowRequest\032\017.FollowResponse\"\000\0227\n\014M" +
      "IsFollowing\022\021.MIsFollowRequest\032\022.MIsFoll",
      "owResponse\"\000\0226\n\013MIsFollower\022\021.MIsFollowR" +
      "equest\032\022.MIsFollowResponse\"\000\022C\n\020GetFollo" +
      "wingList\022\025.GetFollowListRequest\032\026.GetFol" +
      "lowListResponse\"\000\022B\n\017GetFollowerList\022\025.G" +
      "etFollowListRequest\032\026.GetFollowListRespo" +
      "nse\"\000\022@\n\rGetFriendList\022\025.GetFollowListRe" +
      "quest\032\026.GetFollowListResponse\"\000\022E\n\016GetFo" +
      "llowCount\022\027.MGetFollowCountRequest\032\030.MGe" +
      "tFollowCountResponse\"\000B<\n%violet.action." +
      "common.proto_gen.actionP\001Z\021/proto_gen/ac",
      "tionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseResp_descriptor,
        new java.lang.String[] { "StatusCode", "StatusMessage", });
    internal_static_FollowRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FollowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", });
    internal_static_FollowResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FollowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FollowResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_MIsFollowRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MIsFollowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MIsFollowRequest_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserIds", });
    internal_static_MIsFollowResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MIsFollowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MIsFollowResponse_descriptor,
        new java.lang.String[] { "IsFollowing", "IsFollower", "BaseResp", });
    internal_static_MIsFollowResponse_IsFollowingEntry_descriptor =
      internal_static_MIsFollowResponse_descriptor.getNestedTypes().get(0);
    internal_static_MIsFollowResponse_IsFollowingEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MIsFollowResponse_IsFollowingEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MIsFollowResponse_IsFollowerEntry_descriptor =
      internal_static_MIsFollowResponse_descriptor.getNestedTypes().get(1);
    internal_static_MIsFollowResponse_IsFollowerEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MIsFollowResponse_IsFollowerEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GetFollowListRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetFollowListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFollowListRequest_descriptor,
        new java.lang.String[] { "UserId", "MinTime", "MaxTime", "Count", });
    internal_static_GetFollowListResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetFollowListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetFollowListResponse_descriptor,
        new java.lang.String[] { "UserIds", "Total", "HasMore", "BaseResp", });
    internal_static_MGetFollowCountRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_MGetFollowCountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MGetFollowCountRequest_descriptor,
        new java.lang.String[] { "UserIds", "NeedFollowing", "NeedFollower", "NeedFriend", });
    internal_static_MGetFollowCountResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_MGetFollowCountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MGetFollowCountResponse_descriptor,
        new java.lang.String[] { "FollowingCount", "FollowerCount", "FriendCount", "BaseResp", });
    internal_static_MGetFollowCountResponse_FollowingCountEntry_descriptor =
      internal_static_MGetFollowCountResponse_descriptor.getNestedTypes().get(0);
    internal_static_MGetFollowCountResponse_FollowingCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MGetFollowCountResponse_FollowingCountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MGetFollowCountResponse_FollowerCountEntry_descriptor =
      internal_static_MGetFollowCountResponse_descriptor.getNestedTypes().get(1);
    internal_static_MGetFollowCountResponse_FollowerCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MGetFollowCountResponse_FollowerCountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_MGetFollowCountResponse_FriendCountEntry_descriptor =
      internal_static_MGetFollowCountResponse_descriptor.getNestedTypes().get(2);
    internal_static_MGetFollowCountResponse_FriendCountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MGetFollowCountResponse_FriendCountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
