// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public interface BaseRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BaseResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.StatusCode StatusCode = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>.StatusCode StatusCode = 1;</code>
   */
  violet.action.common.proto_gen.action.StatusCode getStatusCode();

  /**
   * <code>string StatusMessage = 2;</code>
   */
  java.lang.String getStatusMessage();
  /**
   * <code>string StatusMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
