// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public interface FollowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FollowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  boolean hasBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseResp getBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseRespOrBuilder getBaseRespOrBuilder();
}
