// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public interface GetFollowListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFollowListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 user_ids = 1;</code>
   */
  java.util.List<java.lang.Long> getUserIdsList();
  /**
   * <code>repeated int64 user_ids = 1;</code>
   */
  int getUserIdsCount();
  /**
   * <code>repeated int64 user_ids = 1;</code>
   */
  long getUserIds(int index);

  /**
   * <code>int64 total = 2;</code>
   */
  long getTotal();

  /**
   * <code>bool has_more = 3;</code>
   */
  boolean getHasMore();

  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  boolean hasBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseResp getBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseRespOrBuilder getBaseRespOrBuilder();
}
