// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public interface GetUserInfosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetUserInfosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .UserInfo user_infos = 1;</code>
   */
  java.util.List<violet.action.common.proto_gen.action.UserInfo> 
      getUserInfosList();
  /**
   * <code>repeated .UserInfo user_infos = 1;</code>
   */
  violet.action.common.proto_gen.action.UserInfo getUserInfos(int index);
  /**
   * <code>repeated .UserInfo user_infos = 1;</code>
   */
  int getUserInfosCount();
  /**
   * <code>repeated .UserInfo user_infos = 1;</code>
   */
  java.util.List<? extends violet.action.common.proto_gen.action.UserInfoOrBuilder> 
      getUserInfosOrBuilderList();
  /**
   * <code>repeated .UserInfo user_infos = 1;</code>
   */
  violet.action.common.proto_gen.action.UserInfoOrBuilder getUserInfosOrBuilder(
      int index);
}
