// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/action.proto

package violet.action.common.proto_gen.action;

public interface MIsFollowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MIsFollowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, bool&gt; is_follower = 1;</code>
   */
  int getIsFollowerCount();
  /**
   * <code>map&lt;int64, bool&gt; is_follower = 1;</code>
   */
  boolean containsIsFollower(
      long key);
  /**
   * Use {@link #getIsFollowerMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Boolean>
  getIsFollower();
  /**
   * <code>map&lt;int64, bool&gt; is_follower = 1;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Boolean>
  getIsFollowerMap();
  /**
   * <code>map&lt;int64, bool&gt; is_follower = 1;</code>
   */

  boolean getIsFollowerOrDefault(
      long key,
      boolean defaultValue);
  /**
   * <code>map&lt;int64, bool&gt; is_follower = 1;</code>
   */

  boolean getIsFollowerOrThrow(
      long key);

  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  boolean hasBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseResp getBaseResp();
  /**
   * <code>.BaseResp baseResp = 255;</code>
   */
  violet.action.common.proto_gen.action.BaseRespOrBuilder getBaseRespOrBuilder();
}
