// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/im.proto

package violet.action.common.proto_gen.im;

public interface MessageSendResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:im.MessageSendResponse)
        com.google.protobuf.MessageOrBuilder {
}
